# Лабораторная работа №5. Разработка единого подхода к предварительной обработки данных.

__Цель лабораторной работы:__ изучение теоретических принципов и инструментальных редств для построения пайплайна для предварительной обработки данных.

## Методика выполения работы

1. Подберите набор данных на ресурсах [5-7] и согласуйте свой выбор с преподавателем. Студент может предложить синтезированный набор данных.

2. Реализуйте первичную обработку данных загруженного набора. Выполните полный спектр операций для загруженного набора данны: загрузка, визуализация, обработка пропущенных значений, обработка категориальных данных и разделение выборки на тестовую и тренировочную.

In [9]:
# Загрузка данных
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Data5.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [27]:
# Визуализация данных
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print('Матрица признаков:\n', x)
print()
print('Зависимая переменная:\n', y)

Матрица признаков:
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

Зависимая переменная:
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [43]:
# Обработка категориальных данных
from sklearn.preprocessing import LabelEncoder

labelencoder_y = LabelEncoder()
y_transformed = labelencoder_y.fit_transform(y)
print(y_transformed)

[0 1 0 0 1 1 0 1 0 1]


In [42]:
# Обработка категориальных данных и заполнение пропусков
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

transformers = [
    ('onehot', OneHotEncoder(), [0]),
    ('imp', SimpleImputer(), [1, 2])
]
ct = ColumnTransformer(transformers)
x_transformed = ct.fit_transform(x)
print(x_transformed.shape)
x_transformed


(10, 5)


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [46]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_transformed, y_transformed, test_size=0.2, random_state=42)
print('Тренировочкая выборка:', x_train, y_train, sep='\n')
print('Тестовая выборка:', x_test, y_test, sep='\n')

Тренировочкая выборка:
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]]
[1 0 1 0 1 1 0 0]
Тестовая выборка:
[[0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]]
[0 1]


In [48]:
# Можно преобразовать полученный многомерный массив обратно в Dataframe
x_data = pd.DataFrame(
    x_test,
    columns=['C1', 'C2', 'C3', 'Age', 'Salary'])
y_date = pd.DataFrame(
    y_test,
    columns=['Purchased']
)
print(x_data, y_date, sep='\n')

    C1   C2   C3   Age   Salary
0  0.0  1.0  0.0  50.0  83000.0
1  0.0  0.0  1.0  27.0  48000.0
   Purchased
0          0
1          1


## Контрольные вопросы

1. Какая библиотека python предназначена для управления наборами данных: numpy, pandas, sklearn, opencv, matplotlib?
    
Pandas - библиотека Python, специально разработанная для работы с наборами данных. Она предоставляет удобные структуры данных и инструменты для манипулирования, очистки, анализа и визуализации данных.

2. Какая стратегия является нежелательной при обработке пропусков в данных?
    - удаление строк, содержащих пропуски в данных;
    
        Удаление целых строк из-за пропущенных значений может привести к потере информации и смещению результатов анализа.

3. Обоснуйте ответ на следующую проблему предварительной обработки данных: имеется независимая категориальная переменная y, которая представляет собой категориальный признак, опеределнный на домене {C#, Java, Python, R}. Нужно ли применять к данному целевому признаку OneHotEncoder?

Да, к данному целевому признаку необходимо применять OneHotEncoder.

OneHotEncoder преобразует категориальные переменные в числовые представления, что необходимо для большинства алгоритмов машинного обучения.

4. Поясните принцип разбиения набора данных на обучающую и тестовую выборку. Какое соотношение «тестовая:обучающая» наиболее оптимально: 20:80, 50:50, 25:75, 5:95, 40:30?

Разбиение набора данных на обучающую и тестовую выборку - это важный этап подготовки данных к машинному обучению. Обучающая выборка используется для обучения модели, тестовая выборка - для оценки ее производительности на невиданных ранее данных. Наиболее оптимальное соотношение зависит от конкретного набора данных и задачи.

Общее правило: больше данных в обучающей выборке - лучше, но при этом необходимо оставить достаточно данных для тестовой выборки, чтобы объективно оценить модель.

Часто используемые соотношения: 80/20, 70/30, 60/40.

5. Какой код лучше использовать при загрузке данных из csv-файла?
    - dataset = read_csv(“data.csv”)

Pandas предоставляет функцию read_csv специально для загрузки данных из csv-файлов. Другие варианты могут быть доступны в других библиотеках, но pd.read_csv из pandas - это общепринятый и рекомендованный способ.
